### ISSUE TITLE
Localize should update components when preferred language changes

### ISSUE THREAD

**Issue by xdev1** [shoelace-style/localize#10]
I guess, adding the following lines should do the job (=> [more info](https://developer.mozilla.org/en-US/docs/Web/API/Window/languagechange_event))

```js
window.addEventListener('languagechange', () => {
  if (!document.documentElement.lang) {
    update();
  }
});
```

**Comment by claviska** [comment]
Sadly, this event doesn't fire when the `lang` attribute changes. It seems to only fire when the browser's locale changes, which is probably not very common as you need to go into your browser settings (or OS settings if it's set to the same as the OS) and change it there.

I don't think there's anything to do here, as we're adding extra bytes for an edge case that will rarely ever happen. Plus, users that do change their browser's language while pages are open will probably expect to restart or at least refresh the page, at which time the new locale will be detected.

Unless I'm misunderstanding this event, I don't think the benefit is worth the cost in this case.

**Comment by xdev1** [comment]
> It seems to only fire when the browser's locale changes

Yes, for sure

> Sadly, this event doesn't fire when the lang attribute changes

Yes, for sure, but why is this "sad", the `lang` attribute will already be handled by the `MutationObserver`?

> that will rarely ever happen

Yes, for sure

> the cost 

The "cost" is a few additional bytes in a (likely compressed) data stream :wink:

No big deal, I was just wondering why this is missing in `index.ts` - surely not a very important feature.

Okay, I'll close this issue then.

**Comment by claviska** [comment]
> Yes, for sure, but why is this "sad", the lang attribute will already be handled by the MutationObserver?

It would be nice if this got triggered on the element on which the language changes. Then we could ditch the Mutation Observer altogether.

Plus, we’ll need something like it if my proposal for `Element.currentLang` ever gets accepted.
