### ISSUE TITLE
Region detection algorithm not always working properly

### ISSUE THREAD

**Issue by xdev1** [shoelace-style/localize#16]
Great Britain allows two different valid time formats:
* The 24-hour time format:  14:34
* The 12-hour time format: 2:34 pm

`Intl` uses the 24-hour time format for locale `en-GB`.
If you want to use the 12-hour time format for GB then you have to use locale `en-GB-u-hc-h12`.
Please find [here](https://www.typescriptlang.org/play?#code/MYewdgzgLgBANiYBDOBTCMC8MDaByVMAWgHEAhPAGhgOPKIFciALYFgRgCYqbCfbGLNsy54AugG4AUGlhwAlmHRZcAIlWSpMxCnQA6AGYgATgFEkwZgAoEyNFgB8UmPEX6ADgwjXbumAGoaAC4AHTA8AJglAHcYAEkwKDg9ABEkKFQAFXkAW1QAMRMc9JsdNGoAb2cXGABPVCRjIJowBjzjeWAqapcc8ChmZrxOIgATeQBzeShumphRpFqhkfGpmcoemGYQBiaaFcnp2ZqcxQYM5bHDmeqAXwBKQyKSmJg0jKtOAAZOTmov6gAZnY1HYABZqGDAf97rCpPdpDI3BA9J5vFY8HgEVJQJAQGg9MA0I0rNjcRB8ag9AgJjZkXoAFYgRRWVRhIgcsKqWESIA) a litte demo.

So now assume you are using locale `en-GB-u-hc-h12`. Then this line

https://github.com/shoelace-style/localize/blob/421744e6be069d92cf65b4e52e05a979a72cb34a/src/index.ts#L120

will fail to detect the proper code (which should be "en-gb").

Please find [here](https://codesandbox.io/s/region-bug-hjsqyf?file=/src/index.ts) a little demo that shows one case where that bug leads to wrong i18n behavior.

It might be a good idea to  use `new Intl.Locale('en-GB-u-hc-h12')` (see [here](https://caniuse.com/mdn-javascript_builtins_intl_locale) and [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale)).

**Comment by claviska** [comment]
Just a heads up — 3.0.2 detects the region correctly but fails to prepend the language code to it. 🤦🏻‍♂️

Please use 3.0.3 instead, which works as intended.
