### ISSUE TITLE
Localize really needs something like `i18next.exists(...)`

### ISSUE THREAD

**Issue by xdev1** [shoelace-style/localize#17]
Currently it's not possible in `Localize` to check whether a translation for a given key is available or not. Especially it should be possible to check the existence with ignoring the fallback language.

With [`i18next`](https://www.i18next.com/overview/api#exists) you can do something like the following (I do not know if this is the best solution, but at least it works):

```ts
i18next.exists('some-key', {
  fallbackLng: i18next.language
})
```

Maybe something like the following?

```ts
  // this will include the fallback language
  localizeController.exists('some-key')

  // this will exclude the fallback language
  localizeController.exists('some-key', {
    fallbackLang: null
  })

  // or maybe
  localizeController.exits('some-key', {
    includeFallback: false
  })
```

A common use case where something like this is very important are error messages: If error 123 hast been thrown, then first check for the specific error message with `error-123` ... if that fails, then use the generic error message given by `error`.
Needed for Shoelace, for example, if you want component specific validation messages in app language instead of browser UI language.

Here's a litte i18next demo: https://codesandbox.io/s/exists-demo-xiwtdi?file=/src/index.ts

**Comment by claviska** [comment]
Good idea. Added in cbd8b74. The function returns a boolean and all parameters are optional.

```ts
if (this.localize.exists('yourTerm')) {
  // term exists
}
```

If you want to include the fallback in the check:

```ts
this.localize.exists('yourTerm', {
  includeFallback: true
})
```

If you want to check an arbitrary translation:

```ts
this.localize.exists('yourTerm', {
  lang: 'de'
})
```
