### ISSUE TITLE
Language codes with underscores throw a `RangeError`

### ISSUE THREAD

**Issue by claviska** [shoelace-style/localize#20]
[From the Shoelace Discord:](https://discord.com/channels/739437527907303535/1156331724771430470/1156331724771430470)

> Hi everybody, I came across a problem today where I have somebody using something I built with shoelace, and they're getting a "rangeError incorrect locale information" translation error. When I looked at the page it was loading on, the language was set to nl_NL. If I manually set the language to nl-NL it works, or if I use the translate in Chrome it works, but it looks like it's not reading the underscore in the locale as being interchangeable with a hyphen.  It's an app that's getting embedded on his page, so I can't control what language is being used. Can we get shoelace to read underscores in language codes, or is there a way to ignore the language and fall back to english if it can't interpret the language correctly (not just if it can't find the right translations)?

[Per LDML](https://unicode.org/reports/tr35/#unicode-locale-identifier), it looks like both the underscore and the hyphen are acceptable:

> The identifiers can vary in case and in the separator characters. The "-" and "_" separators are treated as equivalent, although "-" is preferred.

**Comment by johnfactotum** [comment]
The value of the `lang` attribute "must be a valid BCP 47 language tag, or the empty string" according to the [HTML spec](https://html.spec.whatwg.org/multipage/dom.html#attr-lang). The use of `_` in Unicode locale identifiers is not BCP 47-compatible. So `lang="nl_NL"` would be invalid.
